---
- hosts: all
  remote_user: root

  tasks:
  - name: apt update
    apt:
      update_cache: yes
      upgrade: yes

  - name: install nginx
    apt:
      pkg: nginx

  - name: install nodejs
    apt:
      pkg: nodejs

  - name: install npm
    apt:
      pkg: npm

  - name: install npm pm2
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: install express
    npm:
      name: express
      global: yes

  - name: run app in background
    command: pm2 start /vagrant/app/app.js
